name: Test and Lint

on: ['push']

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [12, 14, 16]
        typescript: ['4.3', '4.4', '4.5']
    name: Test with TypeScript ${{ matrix.typescript }} on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm  install typescript@${{ matrix.typescript }} --save-dev
      - run: npx nx run-many --target=build --all
      - run: npx nx run-many --target=test --all
      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: coverage/**/junit*.xml

  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: ['14']
    name: Lint on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npx nx run-many --target=lint --all
