# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test and Lint

on:
  push:
    paths-ignore:
      - .devcontainer/**
      - .github/**
      - .vscode/**
      - .husky/**
    branches-ignore:
      - main

jobs:
  test-multi-version:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [12, 14, 16]
        typescript: ['4.3', '4.4', '4.5']
    name: Test with TypeScript ${{ matrix.typescript }} on Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: NPM Install
        run: npm ci
      - name: Install Typescript ${{ matrix.typescript }}
        run: npm  install typescript@${{ matrix.typescript }} --save-dev
      - name: Build
        run: npx nx run-many --target=build --all
      - name: Install
        run: npx nx run-many --target=test --all

  lint:
    runs-on: ubuntu-20.04
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: NPM Install
        run: npm ci
      - name: Lint
        run: npx nx run-many --target=lint --all
