# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_artifact:
    name: Build Release Artifact
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Install
        run: npm ci
      - id: project_info
        name: Parse Project Info
        run: |
          PROJECT=$(echo ${{ github.ref_name }} | sed 's/\(.*\)-\([0-9]\+\.[0-9]\+\.[0-9]\+\)/\1/')
          VERSION=$(echo ${{ github.ref_name }} | sed 's/\(.*\)-\([0-9]\+\.[0-9]\+\.[0-9]\+\)/\2/')
          PROJECT_REL_PATH=$(cat workspace.json | jq -r ".projects[\"$PROJECT\"]")
          PROJECT_PATH=$(pwd)/$PROJECT_REL_PATH
          DIST_PATH=$(pwd)/dist/$PROJECT_REL_PATH
          echo "::echo::on"
          echo "::set-output name=name::$PROJECT"
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=path::$PROJECT_PATH"
          echo "::set-output name=dist::$DIST_PATH"
      - name: Build Release for ${{ github.ref_name }}
        run: |
          npx nx run ${{ steps.project_info.outputs.name }}:build
      - id: package
        name: Create Release Package for ${{ github.ref_name }}
        run: |
          cd ${{ steps.project_info.outputs.dist }}
          PACKAGE_NAME=$(npm pack)
          PACKAGE_PATH=$(pwd)/$PACKAGE_NAME
          echo "::echo::on"
          echo "::set-output name=path::$PACKAGE_PATH"
          echo "::set-output name=name::$PACKAGE_NAME"
      - name: Create Release Artifact for ${{ github.ref_name }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.ref_name }}
          path: ${{ steps.package.outputs.path }}
    outputs:
      project: ${{ steps.project_info.outputs.name }}
      version: ${{ steps.project_info.outputs.version }}
      project_path: ${{ steps.project_info.outputs.path }}
      dist_path: ${{ steps.project_info.outputs.dist }}
      package_name: ${{ steps.package.outputs.name }}

  create_release:
    needs: [build_artifact]
    name: Create Release
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Release Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.ref_name }}
      - id: release
        name: Create Release for ${{ github.ref_name}}
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body_path: ${{ format('{0}/{1}', needs.build_artifact.outputs.project_path, 'CHANGELOG.md') }}
      - name: Upload Artifact to Release for ${{ github.ref_name }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ needs.build_artifact.outputs.package_name }}
          asset_name: ${{ needs.build_artifact.outputs.package_name }}
          asset_content_type: application/gzip
