name: Test and Lint

on: ['push']

jobs:
  test:
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        node: [12, 14, 16]
        typescript: ['4.3', '4.4']
    name: Test with TypeScript ${{ matrix.typescript }} on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm  install typescript@${{ matrix.typescript }} --save-dev
      - run: npx nx run-many --target=build --all
      - run: npx nx run-many --target=test --all

  lint:
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        node: ['14']
    name: Lint on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: nx run-many --target=lint --all
